name: reusable_bloc_base
description: "A reusable base for BLoC classes"
version: 0.0.2
repository: https://github.com/ndnam198/my_flutter_packages.git

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  any_state: ^0.0.4+2
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
