include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    lines_longer_than_80_chars: false
    require_trailing_commas: true
    avoid_setters_without_getters: false
    public_member_api_docs: true


