name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  reusable_bloc_base:
    path: ../
  flutter_bloc: ^8.1.6
  loader_overlay: ^4.0.3
  toastification: ^2.3.0
  flutter_spinkit: ^5.2.1
  any_state: ^0.0.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
