name: any_state
description: "Simple yet easily extended state class declaration that supports localizations"
version: 0.0.4+2
repository: https://github.com/ndnam198/my_flutter_packages.git/any_state

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
