name: example
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  any_state:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
